substitutions:
  name: "airlytix"
  friendly_name: "Airlytix"
  project_name: "airlytix.es1"
  project_version: "0.0.5"
  indicator_max_power: "0.1"
  sht4x_temperature_offset: "0"
  sht4x_humidity_offset: "0"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32dev
  framework:
    type: arduino

#logger:

api:

ota:

dashboard_import:
  package_import_url: github://airlytix/configuration/airlytix-es1-rev1.0.yaml@beta
  import_full_config: false

wifi:
  ap:
    password: "tbJWe4T7rD"

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

<<: !include hardware/es1/rev1.0.yaml

packages:
  indicator_led: !include partial_configs/indicator_led.yaml
  diagnostics: !include partial_configs/diagnostics.yaml
  temp_sensor: !include partial_configs/sensors.yaml
  state: !include partial_configs/state.yaml

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - output.turn_off: status_led_2
              else:
                - output.turn_on: status_led_2
                - delay: 500ms
                - output.turn_off: status_led_2
                - delay: 500ms
        else:
          - output.turn_on: status_led_2
          - delay: 200ms
          - output.turn_off: status_led_2
          - delay: 200ms

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

# Logger must be at least debug (default)
logger:
  level: debug