substitutions:
  name: "airlytix"
  friendly_name: "Airlytix"
  project_name: "airlytix.es1"
  project_version: "1.0.0"
  indicator_max_power: "0.1"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

dashboard_import:
  package_import_url: github://airlytix/configuration/airlytix-es1-rev1.0.yaml@main
  import_full_config: false

wifi:
  ap:
    password: "tbJWe4T7rD"

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

<<: !include hardware/es1/rev1.0.yaml

packages:
  indicator_led: !include components/indicator_led.yaml

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - output.turn_off: status_led_2
              else:
                - output.turn_on: status_led_2
                - delay: 500ms
                - output.turn_off: status_led_2
                - delay: 500ms
        else:
          - output.turn_on: status_led_2
          - delay: 200ms
          - output.turn_off: status_led_2
          - delay: 200ms