esphome:
  on_boot: 
    then:
      - if: 
          condition:
            - light.is_on: indicator_light
          then:
            - light.turn_on:
                id: indicator_light_internal
                brightness: !lambda return id(indicator_light).remote_values.get_brightness();
                blue: 1
                red: 0
                green: 0
                effect: Pulse


light:
  - platform: monochromatic
    id: indicator_light
    name: "Indicator Light"
    output: dummy_output
    default_transition_length: 0s
    restore_mode: RESTORE_AND_ON
    on_turn_on: 
      then:
        - light.turn_on: 
            id: indicator_light_internal
            transition_length: 0s
            brightness: !lambda return id(indicator_light).remote_values.get_brightness();
    on_turn_off: 
      then:
        - light.turn_off: indicator_light_internal        
    on_state:
      then:
        - light.control: 
            id: indicator_light_internal
            brightness: !lambda return id(indicator_light).remote_values.get_brightness();

  - platform: rgb
    id: indicator_light_internal
    name: "Indicator_light"
    red: indicator_led_r
    green: indicator_led_g
    blue: indicator_led_b
    internal: true
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%


output:
  - platform: template
    id: dummy_output
    type: float
    write_action:
      - lambda: ''
