esphome:
  includes:
    - components/custom/veml6040/VEML6040.h

external_components:
  - source: github://stas-sl/esphome-sound-level-meter@v1.0.3


sensor:
  - platform: scd4x
    ambient_pressure_compensation_source: dps310_pressure
    co2:
      name: "CO2"
      id: "scd4x_co2"
    temperature:
      disabled_by_default: True
      internal: True
      id: "scd4x_temperature"
    humidity:
      disabled_by_default: True
      internal: True
      id: "scd4x_humidity"

  - platform: sht4x
    temperature:
      id: sht4x_temperature
      name: "Temperature"
      filters: 
        - offset: ${sht4x_temperature_offset}
      on_value: 
        then:
          - component.update: internal_temperature_state
    humidity:
      id: sht4x_humidity
      name: "Humidity"
      filters: 
        - offset: ${sht4x_humidity_offset}
      on_value: 
        then:
          - component.update: internal_humidity_state
    update_interval: 60s


  - platform: dps310
    temperature:
      disabled_by_default: True
      internal: True
      id: "dps310_temperature"
    pressure:
      name: "Pressure"
      id: "dps310_pressure"
    address: 0x77
    update_interval: 120s

  - platform: sen5x
    id: sen55
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "sen55_pm_1_0"
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: internal_pm_1_0_state
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "sen55_pm_2_5"
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: internal_pm_2_5_state
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "sen55_pm_4_0"
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: internal_pm_4_0_state
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "sen55_pm_10_0"
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: internal_pm_10_0_state
    temperature:
      disabled_by_default: true
      internal: true
      id: "sen55_temperature"
    humidity:
      disabled_by_default: true
      internal: true
      id: "sen55_humidity"
    voc:
      name: "VOC"
      id: "sen55_voc"
    nox:
      name: "NOX"
      id: "sen55_nox"
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 60s

  
  - platform: custom
    lambda: |-
      auto veml6040 = new VEML6040CustomSensor();
      App.register_component(veml6040);
      return {veml6040->ambient_light, veml6040->color_temp};
  
    sensors:
    - name: "Ambient Light"
      id: veml6040_lx
      unit_of_measurement: lx
      device_class: ILLUMINANCE
      state_class: measurement
      accuracy_decimals: 2
    - name: "Ambient Light CCT"
      id: veml6040_cct
      state_class: measurement

sound_level_meter:
  update_interval: 60s           # default: 60s
  is_on: true                    # default: true
  buffer_size: 1024             # default: 1024
  warmup_interval: 500ms        # default: 500ms
  task_stack_size: 4096         # default: 4096
  task_priority: 2              # default: 2
  task_core: 1                  # default: 1
  mic_sensitivity: -26dB        # default: empty
  mic_sensitivity_ref: 94dB     # default: empty
  offset: 0dB                   # default: empty
  groups:

        # group 1.2 (A-weighting)
        - filters:
            # for now only SOS filter type is supported, see math/filter-design.ipynb
            # to learn how to create or convert other filter types to SOS
            - type: sos
              coeffs:
                # A-weighting:
                #       b0           b1            b2             a1            a2
                - [ 0.16999495 ,  0.741029   ,  0.52548885 , -0.11321865 , -0.056549273]
                - [ 1.         , -2.00027    ,  1.0002706  , -0.03433284 , -0.79215795 ]
                - [ 1.         , -0.709303   , -0.29071867 , -1.9822421  ,  0.9822986  ]
          sensors:
            - type: eq
              name: Ambient Sound Level (LAeq_1min)
              id: soundlevel_laeq_1min
              unit_of_measurement: dBA
            - type: peak
              name: Ambient Sound Level (LApeak_1min)
              id: soundlevel_lapeak_1min
              unit_of_measurement: dBA