substitutions:
  name: "airlytix-es1"
  friendly_name: "Airlytix"
  project_name: "airlytix.es1"
  project_version: "1.0.0"
  indicator_max_power: "1"
  sht4x_temperature_offset: "-6.5"
  sht4x_humidity_offset: "20"
  sen55_temperature_offset: "-1.5"
  sen55_humidity_offset: "0"
  veml6040_glass_attenuation: "0.42"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:

api:

ota:

dashboard_import:
  package_import_url: github://airlytix/configuration/airlytix-es1.yaml@main
  import_full_config: false

external_components:
  - source: github://airlytix/esphome-sound-level-meter@main
  - source: github://airlytix/configuration@main

wifi:
  ap:

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

<<: !include ../hardware/es1/rev1.0.yaml

packages:
  indicator_led: !include ../partial_configs/indicator_led.yaml
  diagnostics: !include ../partial_configs/diagnostics.yaml
  sensors: !include ../partial_configs/sensors.yaml
  state: !include ../partial_configs/state.yaml

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - output.turn_off: status_led_2
              else:
                - output.turn_on: status_led_2
                - delay: 500ms
                - output.turn_off: status_led_2
                - delay: 500ms
        else:
          - output.turn_on: status_led_2
          - delay: 200ms
          - output.turn_off: status_led_2
          - delay: 200ms