name: Generate ESPHome configuration

on:
  push:

  workflow_dispatch:


jobs:
    list-configs:
        runs-on: ubuntu-latest
        outputs:
          names: ${{ steps.set-matrix.outputs.names }}
        steps:
          - uses: actions/checkout@v4.1.1
          - id: set-matrix
            run: |
              echo "names=$(ls configs/*.yaml | xargs -I{} basename {} | sed 's/\.[^.]*$//' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    
    generate-config:
        needs: [list-configs]
        strategy:
            matrix:
                config_file: ${{ fromJson(needs.list-configs.outputs.names) }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Generate ESPHome configuration
              uses: addnab/docker-run-action@v3
              with:
                  image: ghcr.io/esphome/esphome:2024.3.0
                  options: -v ${{ github.workspace }}:/data
                  run: |
                      esphome config /data/configs/${{ matrix.config_file }}.yaml > /data/${{ matrix.config_file }}.yaml

            - name: Commit & Push changes
              uses: EndBug/add-and-commit@v9
              with:
                add: ./${{ matrix.config_file }}.yaml
                message: "[AUTO] Update ESPHome configuration for ${{ matrix.config_file }}"
                push: true
